apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lt-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lt-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50