apiVersion: apps/v1
kind: Deployment
metadata:
  name: lt-deploy
  labels:
    app: lista-de-tarefas
spec:
  selector:
    matchLabels:
      app: lista-de-tarefas
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
        labels:
          app: lista-de-tarefas
    spec:
      containers:
      - name: lista-de-tarefas
        image: aguilerajoao/lista-de-tarefas:1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi" 
            cpu: "500m"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: DB_NAME
        # [START cloud_sql_proxy_secret_host]
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: DB_HOST
        # [END cloud_sql_proxy_secret_host]